apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "1001"
  name: aap-soknad-api
  namespace: aap
  labels:
    team: aap
spec:
  gcp:
    buckets:
      - name: aap-utland-mellomlagring
        retentionPeriodDays: 2
  accessPolicy:
    inbound:
      rules:
        - application: aap-soknad
  tokenx:
    enabled: true
  kafka:
    pool: {{kafka-pool}}
  port: 8080
  cpuThresholdPercentage: 50
  image: {{image}}
  liveness:
    path: /actuator/health/liveness
    initialDelay: 60
  readiness:
    path: /actuator/health/readiness
    initialDelay: 60
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - {{ingress}}
  resources:
    limits:
      cpu: 1500m
      memory: 3072Mi
    requests:
      cpu: 250m
      memory: 1536Mi